# Generated by Django 3.2 on 2021-04-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': False, 'ordering': ['title']},
        ),
    ]
