# Generated by Django 3.2 on 2021-04-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': False, 'ordering': ['rating']},
        ),
    ]
